MONSTERS_DB = {
    "방울숲": {
        "name": "방울숲",
        "level_range": (1, 5),
        "monsters": [
            {
                "id": "slime",
                "name": "슬라임",
                "level": 1,
                "hp": 30,
                "attack": 5,
                "defense": 1,
                "exp": 8,
                "gold": (3, 8),
                "drops": [
                    {"item": "lt_leather_01", "rate": 0.4},
                    {"item": "gt_herb_01",    "rate": 0.3},
                    {"item": "water",         "rate": 0.5},
                ],
            },
            {
                "id": "forest_spider",
                "name": "숲 거미",
                "level": 2,
                "hp": 45,
                "attack": 7,
                "defense": 2,
                "exp": 12,
                "gold": (5, 12),
                "drops": [
                    {"item": "spider_web",   "rate": 0.6},
                    {"item": "lt_tooth_01",  "rate": 0.3},
                    {"item": "poison_sac",   "rate": 0.15},
                ],
            },
            {
                "id": "green_goblin",
                "name": "풀 고블린",
                "level": 3,
                "hp": 60,
                "attack": 10,
                "defense": 3,
                "exp": 18,
                "gold": (8, 18),
                "drops": [
                    {"item": "club",         "rate": 0.1},
                    {"item": "lt_leather_01","rate": 0.4},
                    {"item": "con_bread",    "rate": 0.2},
                ],
            },
            {
                "id": "honey_bear",
                "name": "꿀벌 곰",
                "level": 4,
                "hp": 90,
                "attack": 14,
                "defense": 5,
                "exp": 28,
                "gold": (12, 25),
                "drops": [
                    {"item": "honey",        "rate": 0.5},
                    {"item": "bear_paw",     "rate": 0.25},
                    {"item": "lt_leather_01","rate": 0.5},
                ],
            },
            {
                "id": "bell_sprite",
                "name": "방울 정령",
                "level": 5,
                "hp": 120,
                "attack": 18,
                "defense": 6,
                "exp": 40,
                "gold": (18, 35),
                "drops": [
                    {"item": "mp_crystal",   "rate": 0.2},
                    {"item": "feather",      "rate": 0.45},
                    {"item": "lt_core_01",   "rate": 0.1},
                ],
            },
        ],
    },
    "고블린동굴": {
        "name": "고블린 동굴",
        "level_range": (5, 12),
        "monsters": [
            {
                "id": "goblin_warrior",
                "name": "고블린 전사",
                "level": 5,
                "hp": 140,
                "attack": 22,
                "defense": 8,
                "exp": 55,
                "gold": (20, 40),
                "drops": [
                    {"item": "short_bow",    "rate": 0.08},
                    {"item": "lt_leather_01","rate": 0.5},
                    {"item": "iron_ore",     "rate": 0.3},
                ],
            },
            {
                "id": "goblin_shaman",
                "name": "고블린 주술사",
                "level": 7,
                "hp": 110,
                "attack": 28,
                "defense": 5,
                "exp": 70,
                "gold": (25, 50),
                "drops": [
                    {"item": "mana_herb",    "rate": 0.3},
                    {"item": "bad_score",    "rate": 0.4},
                    {"item": "mp_crystal",   "rate": 0.15},
                ],
            },
            {
                "id": "goblin_king",
                "name": "고블린 대왕",
                "level": 10,
                "hp": 300,
                "attack": 40,
                "defense": 15,
                "exp": 150,
                "gold": (60, 120),
                "drops": [
                    {"item": "hard_horn",    "rate": 0.4},
                    {"item": "iron_ore",     "rate": 0.6},
                    {"item": "copper_ore",   "rate": 0.5},
                    {"item": "re_stone",     "rate": 0.05},
                ],
            },
        ],
    },
    "소금광산": {
        "name": "소금 광산",
        "level_range": (10, 20),
        "monsters": [
            {
                "id": "skeleton",
                "name": "해골 병사",
                "level": 10,
                "hp": 200,
                "attack": 38,
                "defense": 12,
                "exp": 130,
                "gold": (45, 90),
                "drops": [
                    {"item": "coal",         "rate": 0.5},
                    {"item": "iron_ore",     "rate": 0.4},
                    {"item": "rotten_meat",  "rate": 0.3},
                ],
            },
            {
                "id": "salt_golem",
                "name": "소금 골렘",
                "level": 13,
                "hp": 420,
                "attack": 50,
                "defense": 30,
                "exp": 220,
                "gold": (90, 170),
                "drops": [
                    {"item": "silver_ore",   "rate": 0.4},
                    {"item": "sulfur",       "rate": 0.5},
                    {"item": "iron_ore",     "rate": 0.6},
                ],
            },
            {
                "id": "dark_wizard",
                "name": "어둠 마법사",
                "level": 15,
                "hp": 280,
                "attack": 65,
                "defense": 10,
                "exp": 280,
                "gold": (110, 200),
                "drops": [
                    {"item": "eye_of_truth", "rate": 0.1},
                    {"item": "dark_matter",  "rate": 0.05},
                    {"item": "mp_crystal",   "rate": 0.35},
                    {"item": "mana_herb",    "rate": 0.4},
                ],
            },
        ],
    },
}
