RANK_ORDER = ["연습", "F", "E", "D", "C", "B", "A", "9", "8", "7", "6", "5", "4", "3", "2", "1"]

RANK_UP_THRESHOLD = {
    "연습": 200,
    "F":   400,
    "E":   700,
    "D":   1100,
    "C":   1600,
    "B":   2500,
    "A":   4000,
    "9":   6000,
    "8":   8500,
    "7":   11500,
    "6":   15000,
    "5":   19500,
    "4":   25000,
    "3":   32000,
    "2":   40000,
}

COOKING_SKILL = {
    "연습": ["ck_soup_01"],
    "F":   ["ck_soup_01"],
    "E":   ["ck_soup_01", "ck_steak_01"],
    "D":   ["ck_soup_01", "ck_steak_01"],
    "C":   ["ck_soup_01", "ck_steak_01", "ck_special_01"],
    "B":   ["ck_soup_01", "ck_steak_01", "ck_special_01"],
    "A":   ["ck_soup_01", "ck_steak_01", "ck_special_01"],
}

COMBAT_SKILLS = {
    "smash": {
        "name": "스매시",
        "ranks": {r: {} for r in RANK_ORDER},
        "desc": "강력한 단일 타격 스킬. 적에게 큰 피해를 입힌다.",
        "mp_cost": 0,
        "damage_bonus": {
            "연습": 1.1, "F": 1.2, "E": 1.3, "D": 1.5,
            "C": 1.7, "B": 2.0, "A": 2.3, "9": 2.6,
            "8": 3.0, "7": 3.5, "6": 4.0, "5": 4.6,
            "4": 5.3, "3": 6.0, "2": 7.0, "1": 8.0,
        },
    },
    "defense": {
        "name": "디펜스",
        "ranks": {r: {} for r in RANK_ORDER},
        "desc": "방어 자세를 취해 받는 피해를 줄인다.",
        "mp_cost": 0,
        "damage_reduce": {
            "연습": 0.05, "F": 0.08, "E": 0.10, "D": 0.13,
            "C": 0.17, "B": 0.21, "A": 0.25, "9": 0.30,
            "8": 0.35, "7": 0.40, "6": 0.45, "5": 0.50,
            "4": 0.55, "3": 0.60, "2": 0.68, "1": 0.75,
        },
    },
    "counter": {
        "name": "카운터",
        "ranks": {r: {} for r in RANK_ORDER},
        "desc": "적의 공격을 받아내고 반격한다.",
        "mp_cost": 0,
        "counter_multiplier": {
            "연습": 1.5, "F": 1.7, "E": 2.0, "D": 2.3,
            "C": 2.7, "B": 3.2, "A": 3.8, "9": 4.5,
            "8": 5.2, "7": 6.0, "6": 7.0, "5": 8.0,
            "4": 9.0, "3": 10.0, "2": 12.0, "1": 15.0,
        },
    },
    "windmill": {
        "name": "윈드밀",
        "ranks": {r: {} for r in RANK_ORDER},
        "desc": "주변 모든 적을 공격하는 광역 스킬.",
        "mp_cost": 0,
        "aoe_multiplier": {
            "연습": 0.8, "F": 0.9, "E": 1.0, "D": 1.2,
            "C": 1.4, "B": 1.7, "A": 2.0, "9": 2.4,
            "8": 2.9, "7": 3.5, "6": 4.2, "5": 5.0,
            "4": 5.9, "3": 7.0, "2": 8.5, "1": 10.0,
        },
    },
}

MAGIC_SKILLS = {
    "firebolt": {
        "name": "파이어볼트",
        "ranks": {r: {} for r in RANK_ORDER},
        "desc": "불꽃 마법탄을 발사한다.",
        "mp_cost": {
            "연습": 8, "F": 8, "E": 7, "D": 6,
            "C": 5, "B": 5, "A": 4, "9": 4,
            "8": 3, "7": 3, "6": 3, "5": 2,
            "4": 2, "3": 2, "2": 1, "1": 1,
        },
        "damage": {
            "연습": 15, "F": 20, "E": 28, "D": 38,
            "C": 50, "B": 65, "A": 82, "9": 102,
            "8": 125, "7": 152, "6": 183, "5": 218,
            "4": 258, "3": 303, "2": 355, "1": 415,
        },
    },
    "icebolt": {
        "name": "아이스볼트",
        "ranks": {r: {} for r in RANK_ORDER},
        "desc": "얼음 마법탄을 발사하며 적을 둔화시킨다.",
        "mp_cost": {
            "연습": 6, "F": 6, "E": 6, "D": 5,
            "C": 5, "B": 4, "A": 4, "9": 3,
            "8": 3, "7": 3, "6": 2, "5": 2,
            "4": 2, "3": 2, "2": 1, "1": 1,
        },
        "damage": {
            "연습": 12, "F": 16, "E": 22, "D": 30,
            "C": 40, "B": 52, "A": 66, "9": 82,
            "8": 100, "7": 122, "6": 147, "5": 175,
            "4": 207, "3": 243, "2": 284, "1": 330,
        },
    },
    "lightningbolt": {
        "name": "라이트닝볼트",
        "ranks": {r: {} for r in RANK_ORDER},
        "desc": "번개 마법탄을 발사한다. 빠른 시전 속도.",
        "mp_cost": {
            "연습": 10, "F": 10, "E": 9, "D": 8,
            "C": 7, "B": 6, "A": 5, "9": 5,
            "8": 4, "7": 4, "6": 3, "5": 3,
            "4": 2, "3": 2, "2": 2, "1": 1,
        },
        "damage": {
            "연습": 18, "F": 25, "E": 34, "D": 46,
            "C": 60, "B": 78, "A": 99, "9": 123,
            "8": 151, "7": 183, "6": 220, "5": 262,
            "4": 310, "3": 364, "2": 426, "1": 498,
        },
    },
}

RECOVERY_SKILLS = {
    "healing": {
        "name": "힐링",
        "ranks": {r: {} for r in RANK_ORDER},
        "desc": "자신 또는 대상을 회복시킨다.",
        "mp_cost": {
            "연습": 10, "F": 10, "E": 9, "D": 8,
            "C": 7, "B": 6, "A": 5, "9": 5,
            "8": 4, "7": 4, "6": 3, "5": 3,
            "4": 3, "3": 2, "2": 2, "1": 1,
        },
        "heal_amount": {
            "연습": 20, "F": 28, "E": 38, "D": 52,
            "C": 70, "B": 92, "A": 118, "9": 148,
            "8": 183, "7": 224, "6": 271, "5": 325,
            "4": 386, "3": 455, "2": 533, "1": 621,
        },
    },
}

MASTERY_SKILLS = {
    "combat_mastery": {
        "name": "전투 마스터리",
        "desc": "전투 숙련도. 랭크업 시 힘·체력 상승.",
        "stat_bonus": {
            "연습": {"str": 1},
            "F":   {"str": 2},
            "E":   {"str": 3, "max_hp": 5},
            "D":   {"str": 5, "max_hp": 10},
            "C":   {"str": 7, "max_hp": 15},
            "B":   {"str": 10, "max_hp": 20},
            "A":   {"str": 14, "max_hp": 30},
            "9":   {"str": 19, "max_hp": 40},
            "8":   {"str": 25, "max_hp": 55},
            "7":   {"str": 32, "max_hp": 70},
            "6":   {"str": 40, "max_hp": 90},
            "5":   {"str": 50, "max_hp": 115},
            "4":   {"str": 62, "max_hp": 145},
            "3":   {"str": 76, "max_hp": 180},
            "2":   {"str": 93, "max_hp": 220},
            "1":   {"str": 113, "max_hp": 265},
        },
    },
    "cooking_mastery": {
        "name": "요리 마스터리",
        "desc": "요리 숙련도. 랭크업 시 지력·체력 상승.",
        "stat_bonus": {
            "연습": {"int": 1},
            "F":   {"int": 2},
            "E":   {"int": 3, "max_hp": 3},
            "D":   {"int": 5, "max_hp": 5},
            "C":   {"int": 7, "max_hp": 8},
            "B":   {"int": 10, "max_hp": 12},
            "A":   {"int": 14, "max_hp": 17},
            "9":   {"int": 19, "max_hp": 23},
            "8":   {"int": 25, "max_hp": 30},
            "7":   {"int": 32, "max_hp": 38},
            "6":   {"int": 40, "max_hp": 48},
            "5":   {"int": 50, "max_hp": 60},
            "4":   {"int": 62, "max_hp": 74},
            "3":   {"int": 76, "max_hp": 90},
            "2":   {"int": 93, "max_hp": 109},
            "1":   {"int": 113, "max_hp": 131},
        },
    },
    "fishing_mastery": {
        "name": "낚시 마스터리",
        "desc": "낚시 숙련도. 랭크업 시 민첩·운 상승.",
        "stat_bonus": {
            "연습": {"dex": 1},
            "F":   {"dex": 2},
            "E":   {"dex": 3, "luck": 1},
            "D":   {"dex": 5, "luck": 2},
            "C":   {"dex": 7, "luck": 3},
            "B":   {"dex": 10, "luck": 5},
            "A":   {"dex": 14, "luck": 7},
            "9":   {"dex": 19, "luck": 10},
            "8":   {"dex": 25, "luck": 13},
            "7":   {"dex": 32, "luck": 17},
            "6":   {"dex": 40, "luck": 22},
            "5":   {"dex": 50, "luck": 28},
            "4":   {"dex": 62, "luck": 35},
            "3":   {"dex": 76, "luck": 43},
            "2":   {"dex": 93, "luck": 53},
            "1":   {"dex": 113, "luck": 65},
        },
    },
    "composing_mastery": {
        "name": "작곡 마스터리",
        "desc": "음악 숙련도. 랭크업 시 지력·의지 상승.",
        "stat_bonus": {
            "연습": {"int": 1},
            "F":   {"int": 2},
            "E":   {"int": 3, "will": 1},
            "D":   {"int": 5, "will": 2},
            "C":   {"int": 7, "will": 4},
            "B":   {"int": 10, "will": 6},
            "A":   {"int": 14, "will": 9},
            "9":   {"int": 19, "will": 13},
            "8":   {"int": 25, "will": 17},
            "7":   {"int": 32, "will": 22},
            "6":   {"int": 40, "will": 28},
            "5":   {"int": 50, "will": 36},
            "4":   {"int": 62, "will": 45},
            "3":   {"int": 76, "will": 56},
            "2":   {"int": 93, "will": 69},
            "1":   {"int": 113, "will": 85},
        },
    },
    "metallurgy_mastery": {
        "name": "제련 마스터리",
        "desc": "제련 숙련도. 랭크업 시 힘·의지 상승.",
        "stat_bonus": {
            "연습": {"str": 1},
            "F":   {"str": 2},
            "E":   {"str": 3, "will": 1},
            "D":   {"str": 5, "will": 2},
            "C":   {"str": 7, "will": 4},
            "B":   {"str": 10, "will": 6},
            "A":   {"str": 14, "will": 9},
            "9":   {"str": 19, "will": 13},
            "8":   {"str": 25, "will": 17},
            "7":   {"str": 32, "will": 22},
            "6":   {"str": 40, "will": 28},
            "5":   {"str": 50, "will": 36},
            "4":   {"str": 62, "will": 45},
            "3":   {"str": 76, "will": 56},
            "2":   {"str": 93, "will": 69},
            "1":   {"str": 113, "will": 85},
        },
    },
    "rest_mastery": {
        "name": "휴식 마스터리",
        "desc": "휴식 스킬 랭크업 시 의지·최대기력이 상승합니다.",
        "stat_bonus": {
            "연습": {"will": 1},
            "F":   {"will": 1, "max_energy": 5},
            "E":   {"will": 2, "max_energy": 5},
            "D":   {"will": 2, "max_energy": 10},
            "C":   {"will": 3, "max_energy": 10},
            "B":   {"will": 4, "max_energy": 15},
            "A":   {"will": 5, "max_energy": 20},
            "9":   {"will": 6, "max_energy": 25},
            "8":   {"will": 8, "max_energy": 30},
            "7":   {"will": 10, "max_energy": 35},
            "6":   {"will": 12, "max_energy": 40},
            "5":   {"will": 15, "max_energy": 50},
            "4":   {"will": 18, "max_energy": 60},
            "3":   {"will": 22, "max_energy": 70},
            "2":   {"will": 27, "max_energy": 85},
            "1":   {"will": 33, "max_energy": 100},
        },
    },
}

OTHER_SKILLS = {
    "metallurgy": {
        "name": "제련술",
        "desc": "광석을 가공하여 주괴를 만든다.",
        "ranks": {r: {} for r in RANK_ORDER},
    },
    "fishing": {
        "name": "낚시",
        "desc": "물고기를 낚는다.",
        "ranks": {r: {} for r in RANK_ORDER},
    },
    "music": {
        "name": "연주",
        "desc": "악기를 연주하여 버프를 부여한다.",
        "ranks": {r: {} for r in RANK_ORDER},
    },
    "cooking": {
        "name": "요리",
        "desc": "재료를 조합하여 음식을 만든다.",
        "ranks": {r: {} for r in RANK_ORDER},
    },
    "rest": {
        "name": "휴식",
        "desc": "기력 회복 효율을 높입니다.",
        "icon": "💤",
        "ranks": {r: {} for r in RANK_ORDER},
    },
    "crafting": {
        "name": "제작",
        "desc": "재료를 조합하여 장비를 만든다.",
        "icon": "🔨",
        "ranks": {r: {} for r in RANK_ORDER},
    },
    "gathering": {
        "name": "채집",
        "desc": "자연에서 재료를 채집한다.",
        "icon": "🌿",
        "ranks": {r: {} for r in RANK_ORDER},
    },
    "mining": {
        "name": "채광",
        "desc": "광석을 채굴한다.",
        "icon": "⛏",
        "ranks": {r: {} for r in RANK_ORDER},
    },
}

ALL_SKILLS = {
    **COMBAT_SKILLS,
    **MAGIC_SKILLS,
    **RECOVERY_SKILLS,
    **MASTERY_SKILLS,
    **OTHER_SKILLS,
}
